#   __________                      _________ __                 __                 
#   \______   \ ____  ______ ____  /   _____//  |______    ____ |  | __ ___________ 
#    |       _//  _ \/  ___// __ \ \_____  \\   __\__  \ _/ ___\|  |/ // __ \_  __ \
#    |    |   (  <_> )___ \\  ___/ /        \|  |  / __ \\  \___|    <\  ___/|  | \/
#    |____|_  /\____/____  >\___  >_______  /|__| (____  /\___  >__|_ \\___  >__|   
#           \/           \/     \/        \/           \/     \/     \/    \/       

# The locale to use in the /locale folder
# Default: en_US
locale: en_US

# A list of worlds that the plugin is disabled in
# Default:
# - disabled_world_name
disabled-worlds:
- disabled_world_name

stackable-blocks:
- DIAMOND_BLOCK
- GOLD_BLOCK
- DIAMOND_BLOCK
- EMERALD_BLOCK
- LAPIS_BLOCK

# Global entity settings
# Changed values in entity_settings.yml will override these values
global-entity-settings:

  # Should entity stacking be enabled at all?
  # Default: true
  stacking-enabled: true

  # The minumum number of nearby entities required to form a stack
  # Do not set this lower than 2
  # Default: 2
  min-stack-size: 2

  # The maximum number of entities that can be in a single stack
  # Default: 128
  max-stack-size: 128

  # Should the entire stack of entities be killed when the main entity dies?
  # Default: false
  kill-entire-stack-on-death: false

# Settings for if you want to use MySQL for data mangement
mysql-settings:

  # Enable MySQL
  # If false, SQLite will be used instead
  # Default: false
  enabled: false

  # MySQL Database Hostname
  # Default: ''
  hostname: ''

  # MySQL Database Port
  # Default: 3306
  port: 3306

  # MySQL Database Name
  # Default: ''
  database-name: ''

  # MySQL Database User Name
  # Default: ''
  user-name: ''

  # MySQL Database User Password
  # Default: ''
  user-password: ''

  # If the database connection should use SSL
  # You should enable this if your database supports SSL
  # Default: false
  use-ssl: false
