name: SparkStacker
version: @version@
authors: [Esophose]
main: dev.esophose.sparkstacker.SparkStacker
api-version: 1.14
softdepend: [HolographicDisplays, Holograms, CMI, UltimateStacker, WildStacker, StackMob]
permissions:
  sparkstacker.*:
    description: Inherits all plugin permissions
    children:
      sparkstacker.reload: true
      sparkstacker.give: true
      sparkstacker.clearall: true
      sparkstacker.convert: true
      sparkstacker.silktouch: true
  sparkstacker.reload:
    description: Allows using the reload command
    default: op
  sparkstacker.give:
    description: Allows using the give command
    default: op
  sparkstacker.clearall:
    description: Allows using the clearall command
    default: op
  sparkstacker.convert:
    description: Allows using the convert command
    default: op
  sparkstacker.silktouch:
    description: Allows picking up spawners with silk touch
    default: op
